#! /bin/bash

echo "$(/home/antonio/bin/cpu_average.run)"\%
#mpstat  | awk 'NR==4 {print $4}'
#mpstat 1 1 | awk '$3 ~ /CPU/ { for(i=1;i<=NF;i++) { if ($i ~ /%idle/) field=i } } $3 ~ /all/ { printf("%d",100 - $field) }'

if [[ $BLOCK_BUTTON -eq 1 ]]; then
  	i3-msg -q "exec /home/antonio/.config/i3/resources/pstat.py pcpu"
fi

